version: '3'

services:
    backend:
        tty: true
        build: ./backend
        restart: always
        command: nodemon server.js
        volumes: 
            - /backend/node_modules
            - ./backend:/backend
        ports: 
            - 8080:8080
    frontend:
        stdin_open: true
        build: ./frontend
        command: npm run start
        volumes:
            - /frontend/node_modules
            - ./frontend:/frontend
        ports: 
            - 3000:3000
        depends_on: 
            - backend
